apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-my-app-prod
  ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
        nodePort: 30500
  type: NodePort